import type { Metadata } from "next";
import Sidebar from './../ui/adminPage/sideBar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex">
      <div className="flex-1 sticky top-0 h-[100vh]">
        <Sidebar />
      </div>
      <div className="flex-[4_4_0%] w-full">{children}</div>
    </div>
  );
}
